apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  # default. Use `kubectl get sc` too what storage classes are configured
  # for the on prem storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
